### PR TITLE
Add bump for tracking upstream updates + Action for checking + badge for bump

### PR DESCRIPTION
**Pull request by v1gnesh**

### CODE REVIEW

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Review by MikeFultonDev — APPROVED** [review]
Lgtm. Should we be adding this to zopen-generate for new repos ?

**Comment by v1gnesh** [comment]
@MikeFultonDev We should, but that involves boiling down the type of bump statements to a handful (maybe 1-5), and prompting the user at generate time to pick the closest one.

**Comment by MikeFultonDev** [comment]
> @MikeFultonDev We should, but that involves boiling down the type of bump statements to a handful (maybe 1-5), and prompting the user at generate time to pick the closest one.

Can we add a template that they have to fill out? Like we do for check and version? They would then need to fill it out as part of merge of base code? We could provide doc to links to common patterns?

**Comment by v1gnesh** [comment]
Yeah, should do..

**Pull request merged**
