### PR TITLE
clang changes

### PR DESCRIPTION
**Pull request by HarithaIBM**
clang changes , stat.c file had a patch earlier iunder PR1, now with changes in [MVS change](https://github.com/ZOSOpenTools/coreutilsport/compare/main...HarithaIBM:coreutilsport:clang_fix?expand=1#:~:text=if%20defined%20(STATXFS_FILE_SYSTEM_TYPE_MEMBER_NAME)%20%26%26%20!-,defined,-(__MVS__)) created a new patch file under PR10 along with old changes

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
I thought we weren’t turning clang on until everything was working? Should the clang export be enabled?

**Comment by HarithaIBM** [comment]
With xlclang the failed test cases are 67 , which is still less than expected failures. The build is successful for both clang and xlclang with this fix

**Comment by IgorTodorovskiIBM** [comment]
Looks good, thanks!

**Review by MikeFultonDev — APPROVED** [review]
LGTM...

**Review by MikeFultonDev — APPROVED** [review]
LGTM...

**Pull request merged**
